// Quiver directory seed — realistic MCP server data
// Sources: real MCP ecosystem + Polygraph runs

export const mcps = [
  {
    slug: 'context7',
    name: 'Context7',
    package: 'npm/@upstash/context7-mcp',
    description:
      'Up-to-date code docs and examples for any library. Pulls live documentation into the agent context.',
    category: 'docs',
    tags: ['documentation', 'developer', 'context'],
    installs: 184230,
    installs_week: 21450,
    rating: 4.6,
    reviews: 1284,
    grade: 'D',
    grade_reason: 'permission overreach on probe 2.2',
    last_checked: '2026-06-15',
    author: 'Upstash',
    author_handle: '@upstash',
    repo: 'https://github.com/upstash/context7',
    homepage: 'https://context7.com',
    transport: 'stdio',
    runtime: 'Node 20+',
    featured: true,
  },
  {
    slug: 'playwright',
    name: 'Playwright MCP',
    package: 'npm/@playwright/mcp',
    description:
      'Browser automation for agents. Navigate, click, fill, scrape — all in a sandboxed browser context.',
    category: 'browser',
    tags: ['browser', 'automation', 'e2e'],
    installs: 312440,
    installs_week: 38120,
    rating: 4.8,
    reviews: 2102,
    grade: 'A',
    grade_reason: 'all checks passed',
    last_checked: '2026-06-14',
    author: 'Microsoft',
    author_handle: '@playwright',
    repo: 'https://github.com/microsoft/playwright-mcp',
    homepage: 'https://playwright.dev',
    transport: 'stdio',
    runtime: 'Node 20+',
    featured: true,
  },
  {
    slug: 'filesystem',
    name: 'Filesystem',
    package: 'npm/@modelcontextprotocol/server-filesystem',
    description:
      'Sandboxed read/write to a local directory tree. The reference stdio server from the MCP team.',
    category: 'storage',
    tags: ['filesystem', 'sandbox', 'reference'],
    installs: 421009,
    installs_week: 18920,
    rating: 4.5,
    reviews: 3021,
    grade: 'A',
    grade_reason: 'sandbox contained all probes',
    last_checked: '2026-06-15',
    author: 'MCP',
    author_handle: '@modelcontextprotocol',
    repo: 'https://github.com/modelcontextprotocol/servers',
    homepage: 'https://modelcontextprotocol.io',
    transport: 'stdio',
    runtime: 'Node 18+',
    featured: true,
  },
  {
    slug: 'base-mcp',
    name: 'Base MCP',
    package: 'https://mcp.base.org',
    description:
      'Coinbase-hosted onchain + wallet server. Read balances, send tx, swap — all signed by the agent wallet.',
    category: 'crypto',
    tags: ['base', 'wallet', 'onchain', 'coinbase'],
    installs: 96412,
    installs_week: 22810,
    rating: 4.4,
    reviews: 821,
    grade: 'B',
    grade_reason: 'egress unverified — remote server',
    last_checked: '2026-06-15',
    author: 'Coinbase',
    author_handle: '@base',
    repo: null,
    homepage: 'https://mcp.base.org',
    transport: 'http',
    runtime: 'cloud',
    featured: true,
  },
  {
    slug: 'web3auth',
    name: 'Web3Auth MCP',
    package: 'https://mcp.web3auth.io',
    description:
      'Torus-based social-login wallet for agents. End-user signing via Google, Apple, or email.',
    category: 'crypto',
    tags: ['wallet', 'auth', 'social'],
    installs: 41208,
    installs_week: 6210,
    rating: 4.1,
    reviews: 312,
    grade: 'B',
    grade_reason: 'egress not run for this target',
    last_checked: '2026-06-12',
    author: 'Web3Auth',
    author_handle: '@web3auth',
    repo: 'https://github.com/Web3Auth',
    homepage: 'https://web3auth.io',
    transport: 'http',
    runtime: 'cloud',
    featured: false,
  },
  {
    slug: 'goweb3',
    name: 'GoWeb3 MCP',
    package: 'https://mcp.goweb3.fyi/mcp/',
    description:
      'Onboarding & education for web3 — tutorials, gas explainers, signing flows, all surfaced as agent tools.',
    category: 'crypto',
    tags: ['onboarding', 'education', 'web3'],
    installs: 18821,
    installs_week: 3012,
    rating: 4.0,
    reviews: 184,
    grade: 'B',
    grade_reason: 'remote, partial verification',
    last_checked: '2026-06-10',
    author: 'goweb3.fyi',
    author_handle: '@goweb3fyi',
    repo: null,
    homepage: 'https://goweb3.fyi',
    transport: 'http',
    runtime: 'cloud',
    featured: false,
  },
  {
    slug: 'github',
    name: 'GitHub MCP',
    package: 'npm/@modelcontextprotocol/server-github',
    description:
      'Read repos, open issues, review PRs, post comments — all from inside your agent.',
    category: 'developer',
    tags: ['github', 'git', 'review', 'pr'],
    installs: 256301,
    installs_week: 24420,
    rating: 4.7,
    reviews: 1893,
    grade: 'A',
    grade_reason: 'all checks passed',
    last_checked: '2026-06-14',
    author: 'GitHub',
    author_handle: '@github',
    repo: 'https://github.com/modelcontextprotocol/servers',
    homepage: 'https://github.com',
    transport: 'stdio',
    runtime: 'Node 18+',
    featured: true,
  },
  {
    slug: 'postgres',
    name: 'Postgres MCP',
    package: 'npm/@modelcontextprotocol/server-postgres',
    description:
      'Read-only Postgres introspection + a guarded query tool. Schema-aware, parameter-bound.',
    category: 'data',
    tags: ['sql', 'postgres', 'database'],
    installs: 142108,
    installs_week: 12810,
    rating: 4.5,
    reviews: 974,
    grade: 'A',
    grade_reason: 'all checks passed',
    last_checked: '2026-06-13',
    author: 'MCP',
    author_handle: '@modelcontextprotocol',
    repo: 'https://github.com/modelcontextprotocol/servers',
    homepage: 'https://modelcontextprotocol.io',
    transport: 'stdio',
    runtime: 'Node 18+',
    featured: false,
  },
  {
    slug: 'puppeteer',
    name: 'Puppeteer MCP',
    package: 'npm/@modelcontextprotocol/server-puppeteer',
    description:
      'Headless Chrome via Puppeteer. Scrape, screenshot, fill forms — with a clean page object API.',
    category: 'browser',
    tags: ['browser', 'scrape', 'chrome'],
    installs: 89231,
    installs_week: 8120,
    rating: 4.3,
    reviews: 612,
    grade: 'B',
    grade_reason: 'network unverified, sandbox contained',
    last_checked: '2026-06-11',
    author: 'MCP',
    author_handle: '@modelcontextprotocol',
    repo: 'https://github.com/modelcontextprotocol/servers',
    homepage: 'https://pptr.dev',
    transport: 'stdio',
    runtime: 'Node 18+',
    featured: false,
  },
  {
    slug: 'brave-search',
    name: 'Brave Search MCP',
    package: 'npm/@modelcontextprotocol/server-brave-search',
    description:
      'Web + image search via Brave. No tracking, no ads — just clean SERPs for your agent.',
    category: 'search',
    tags: ['search', 'web', 'brave'],
    installs: 64210,
    installs_week: 5912,
    rating: 4.4,
    reviews: 421,
    grade: 'A',
    grade_reason: 'all checks passed',
    last_checked: '2026-06-14',
    author: 'Brave',
    author_handle: '@brave',
    repo: 'https://github.com/modelcontextprotocol/servers',
    homepage: 'https://brave.com/search/api',
    transport: 'stdio',
    runtime: 'Node 18+',
    featured: false,
  },
  {
    slug: 'notion',
    name: 'Notion MCP',
    package: 'npm/@notionhq/mcp',
    description:
      'Read & write Notion pages, databases, blocks. The official server from the Notion team.',
    category: 'productivity',
    tags: ['notion', 'wiki', 'docs'],
    installs: 73820,
    installs_week: 9320,
    rating: 4.5,
    reviews: 583,
    grade: 'A',
    grade_reason: 'all checks passed',
    last_checked: '2026-06-12',
    author: 'Notion',
    author_handle: '@notionhq',
    repo: 'https://github.com/makenotion/notion-mcp',
    homepage: 'https://notion.so',
    transport: 'stdio',
    runtime: 'Node 18+',
    featured: false,
  },
  {
    slug: 'slack',
    name: 'Slack MCP',
    package: 'npm/@modelcontextprotocol/server-slack',
    description:
      'Read channels, post messages, react, thread. Bot scopes only — no DMs, no file reads.',
    category: 'productivity',
    tags: ['slack', 'chat', 'team'],
    installs: 51208,
    installs_week: 4112,
    rating: 4.2,
    reviews: 312,
    grade: 'B',
    grade_reason: 'remote server, egress not run',
    last_checked: '2026-06-13',
    author: 'MCP',
    author_handle: '@modelcontextprotocol',
    repo: 'https://github.com/modelcontextprotocol/servers',
    homepage: 'https://slack.com',
    transport: 'stdio',
    runtime: 'Node 18+',
    featured: false,
  },
];

export const categories = [
  { slug: 'all', label: 'All' },
  { slug: 'docs', label: 'Docs' },
  { slug: 'browser', label: 'Browser' },
  { slug: 'crypto', label: 'Crypto' },
  { slug: 'data', label: 'Data' },
  { slug: 'developer', label: 'Developer' },
  { slug: 'productivity', label: 'Productivity' },
  { slug: 'search', label: 'Search' },
  { slug: 'storage', label: 'Storage' },
];

export const liveFeed = [
  { who: '@quivermcp', action: 'launched', what: 'QUIVER on Virtuals Protocol', kind: 'launch' },
  { who: '@jesse', action: 'submitted', what: 'Bankr MCP', kind: 'submit' },
  { who: '@aaronjmars', action: 'verified', what: 'Aeon runtime', kind: 'verify' },
  { who: '@rootedge', action: 'reviewed', what: 'Context7', kind: 'review', grade: 'D' },
  { who: '@notionhq', action: 'claimed', what: 'Notion MCP listing', kind: 'claim' },
  { who: '@web3auth', action: 'submitted', what: 'Web3Auth MCP', kind: 'submit' },
  { who: '@playwright', action: 'updated', what: 'to v0.4.1', kind: 'update' },
  { who: '@coinbase', action: 'fixed', what: 'C-02 from grade B', kind: 'fix' },
  { who: '@upstash', action: 'requested', what: 're-polygraph', kind: 'request' },
  { who: '@goweb3fyi', action: 'joined', what: 'Quiver as builder', kind: 'join' },
  { who: '@github', action: 'starred', what: 'Quiver repo', kind: 'star' },
];

export const token = {
  symbol: 'QUIVER',
  name: 'quiver',
  chain: 'Base',
  address: '0x5e2d60835011c14a978bc958d6ec31dccc440770',
  decimals: 18,
  supply: 1_000_000_000,
  launched: '2026-06-17',
  launched_on: 'Virtuals Protocol',
  pct: {
    community: 60,
    treasury: 18,
    team: 12,
    liquidity: 7,
    advisors: 3,
  },
  fee_recipient: 'tivajxzk',
};
